<?php

namespace Database\Seeders;

use App\Models\Countries;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['Albania','Balkan Peninsula',FALSE],
            ['Algeria','Northern Africa',FALSE],
            ['American Samoa','Oceania',FALSE],
            ['Andorra','Southern Europe',FALSE],
            ['Angola','Central Africa',FALSE],
            ['Anguilla','Caribbean',FALSE],
            ['Antarctica','Antarctica',FALSE],
            ['Antigua and Barbuda','Caribbean',FALSE],
            ['Argentina','South America',FALSE],
            ['Armenia','Western Asia',FALSE],
            ['Aruba','Caribbean',FALSE],
            ['Australia','Oceania',FALSE],
            ['Austria','Western Europe',FALSE],
            ['Azerbaijan','Caucasus',FALSE],
            ['Bahamas','Caribbean',FALSE],
            ['Bahrain','Middle East',FALSE],
            ['Bangladesh','South-Central Asia',FALSE],
            ['Barbados','Caribbean',FALSE],
            ['Belarus','Eastern Europe',FALSE],
            ['Belgium','Western Europe',FALSE],
            ['Belize','Central America',FALSE],
            ['Benin','West Africa',FALSE],
            ['Bermuda','North America',FALSE],
            ['Bhutan','South-Central Asia',FALSE],
            ['Bolivia','Central South America',FALSE],
            ['Bosnia and Herzegovina','Southern Europe',FALSE],
            ['Botswana','Southern Africa',FALSE],
            ['Brazil','South America',FALSE],
            ['Brunei Darussalam','Southeast Asia',FALSE],
            ['Bulgaria','Balkan',FALSE],
            ['Burkina Faso','West Africa',FALSE],
            ['Burundi','Eastern Africa',FALSE],
            ['Cambodia','South-East Asia',FALSE],
            ['Cameroon','Central Africa',FALSE],
            ['Canada','North America',FALSE],
            ['Cape Verde','West Africa',FALSE],
            ['Cayman Islands','Caribbean',FALSE],
            ['Central African Republic','Central Africa',FALSE],
            ['Chad','Central Africa',FALSE],
            ['Chile','South America',FALSE],
            ['China','Eastern Asia',FALSE],
            ['Christmas Island','Southeast Asia',FALSE],
            ['Cocos [Keeling] Islands','South-East Asia',FALSE],
            ['Colombia','South America',FALSE],
            ['Comoros','Eastern Africa',FALSE],
            ['Democratic Republic of the Congo [Kinshasa]','Central Africa',FALSE],
            ['Congo','Central Africa',FALSE],
            ['Cook Islands','Oceania',FALSE],
            ['Costa Rica','Central America',FALSE],
            ['Ivory Coast','West Africa',FALSE],
            ['Croatia','Balkan Peninsula',FALSE],
            ['Cuba','Caribbean',FALSE],
            ['Cyprus','Mediterranean',FALSE],
            ['Czech Republic','Eastern Europe',FALSE],
            ['Denmark','Northern Europe',FALSE],
            ['Djibouti','Eastern Africa',FALSE],
            ['Dominica','Caribbean',FALSE],
            ['Dominican Republic','Caribbean',FALSE],
            ['East Timor [Timor-Leste]','South-East Asia',FALSE],
            ['Ecuador','South America',FALSE],
            ['Egypt','Africa',FALSE],
            ['El Salvador','Central America',FALSE],
            ['Equatorial Guinea','Central Africa',FALSE],
            ['Eritrea','Eastern Africa',FALSE],
            ['Estonia','Northern Europe',FALSE],
            ['Ethiopia','Eastern Africa',FALSE],
            ['Faroe Islands','Northern Europe',FALSE],
            ['Fiji','Oceania',FALSE],
            ['Finland','Northern Europe',FALSE],
            ['France','Western Europe',FALSE],
            ['French Guiana','South America',FALSE],
            ['French Polynesia','Oceania',FALSE],
            ['French Southern Territories','Southern Indian Ocean',FALSE],
            ['Gabon','Central Africa',FALSE],
            ['The Gambia','West Africa',FALSE],
            ['Georgia','Caucasus',FALSE],
            ['Germany','Western Europe',FALSE],
            ['Ghana','West Africa',FALSE],
            ['Gibraltar','Southern Europe',FALSE],
            ['Greece','Southern Europe',FALSE],
            ['Greenland','North America',FALSE],
            ['Grenada','Caribbean',FALSE],
            ['Guadeloupe','Caribbean',FALSE],
            ['Guam','Oceania',FALSE],
            ['Guatemala','Central America',FALSE],
            ['Guinea','West Africa',FALSE],
            ['Guinea-Bissau','West Africa',FALSE],
            ['Guyana','South America',FALSE],
            ['Haiti','Caribbean',FALSE],
            ['Holy See','Southern Europe',FALSE],
            ['Honduras','Central America',FALSE],
            ['Hong Kong','Eastern Asia',FALSE],
            ['Hungary','Eastern Europe',FALSE],
            ['Iceland','Northern Europe',FALSE],
            ['India','South-Central Asia',FALSE],
            ['Indonesia','South-East Asia',FALSE],
            ['Iran [Islamic Republic of]','South-Central Asia',FALSE],
            ['Iraq','Middle East',FALSE],
            ['Ireland','Northern Europe',FALSE],
            ['Israel','Middle East',FALSE],
            ['Italy','Southern Europe',FALSE],
            ['Ivory Coast','West Africa',FALSE],
            ['Jamaica','Caribbean',FALSE],
            ['Japan','Eastern Asia',FALSE],
            ['Jordan','Middle East',FALSE],
            ['Kazakhstan','Central Asia',FALSE],
            ['Kenya','Eastern Africa',FALSE],
            ['Kiribati','Oceania',FALSE],
            ['North Korea','Eastern Asia',FALSE],
            ['South Korea','Eastern Asia',FALSE],
            ['Kosovo','Southern Europe',FALSE],
            ['Kuwait','Middle East',FALSE],
            ['Kyrgyzstan','Central Asia',FALSE],
            ['Lao','South-East Asia',FALSE],
            ['Latvia','Northern Europe',FALSE],
            ['Lebanon','Middle East',FALSE],
            ['Lesotho','Southern Africa',FALSE],
            ['Liberia','West Africa',FALSE],
            ['Libya','Northern Africa',FALSE],
            ['Liechtenstein','Western Europe',FALSE],
            ['Lithuania','Northern Europe',FALSE],
            ['Luxembourg','Western Europe',FALSE],
            ['Macau','Eastern Asia',FALSE],
            ['Madagascar','Eastern Africa',FALSE],
            ['Malawi','Eastern Africa',FALSE],
            ['Malaysia','Southeast Asia',FALSE],
            ['Maldives','South-Central Asia',FALSE],
            ['Mali','West Africa',FALSE],
            ['Malta','Southern Europe',FALSE],
            ['Marshall Islands','Oceania',FALSE],
            ['Martinique','Caribbean',FALSE],
            ['Mauritania','West Africa',FALSE],
            ['Mauritius','Eastern Africa',FALSE],
            ['Mayotte','Eastern Africa',FALSE],
            ['Mexico','North America',FALSE],
            ['Federal States of','Oceania',FALSE],
            ['Moldova','Eastern Europe',FALSE],
            ['Monaco','Southern Europe',FALSE],
            ['Mongolia','Eastern Asia',FALSE],
            ['Montenegro','Southern Europe',FALSE],
            ['Montserrat','Caribbean',FALSE],
            ['Morocco','Northern Africa',FALSE],
            ['Mozambique','Eastern Africa',FALSE],
            ['Myanmar','Southeast Asia',FALSE],
            ['Namibia','Southern Africa',FALSE],
            ['Nauru','Oceania',FALSE],
            ['Nepal','South-Central Asia',FALSE],
            ['Netherlands','Western Europe',FALSE],
            ['Netherlands Antilles','Caribbean',FALSE],
            ['New Caledonia','Oceania',FALSE],
            ['New Zealand','Oceania',FALSE],
            ['Nicaragua','Central America',FALSE],
            ['Niger','West Africa',FALSE],
            ['Nigeria','West Africa',FALSE],
            ['Niue','Oceania',FALSE],
            ['North Macedonia','Balkan Peninsula',FALSE],
            ['Northern Mariana Islands','Oceania',FALSE],
            ['Norway','Northern Europe',FALSE],
            ['Oman','Middle East',FALSE],
            ['Pakistan','South-Central Asia',FALSE],
            ['Palau','Oceania',FALSE],
            ['Palestinian territories','Middle East',FALSE],
            ['Panama','Central America',FALSE],
            ['Papua New Guinea','Maritime Southeast Asia',FALSE],
            ['Paraguay','Central South America',FALSE],
            ['Peru','South America',FALSE],
            ['Philippines','Southeast Asia',FALSE],
            ['Pitcairn Island','Oceania',FALSE],
            ['Poland','Eastern Europe',FALSE],
            ['Portugal','Southern Europe',FALSE],
            ['Puerto Rico','Caribbean',FALSE],
            ['Qatar','Middle East',FALSE],
            ['Reunion Island','Eastern Africa',FALSE],
            ['Romania','Eastern Europe',FALSE],
            ['Russian Federation','Eastern Europe',FALSE],
            ['Rwanda','Eastern Africa',FALSE],
            ['Saint Kitts and Nevis','Caribbean',FALSE],
            ['Saint Lucia','Caribbean',FALSE],
            ['Saint Vincent and the Grenadines','Caribbean',FALSE],
            ['Samoa','Oceania',FALSE],
            ['San Marino','Southern Europe',FALSE],
            ['Sao Tome and Principe','Central Africa',FALSE],
            ['Saudi Arabia','Middle East',FALSE],
            ['Senegal','West Africa',FALSE],
            ['Serbia','Southern Europe', TRUE],
            ['Seychelles','Eastern Africa',FALSE],
            ['Sierra Leone','West Africa',FALSE],
            ['Singapore','Southeast Asia',FALSE],
            ['Slovakia [Slovak Republic]','Eastern Europe',FALSE],
            ['Slovenia','Southern Europe',FALSE],
            ['Solomon Islands','Oceania',FALSE],
            ['Somalia','Eastern Africa',FALSE],
            ['South Africa','Southern Africa',FALSE],
            ['South Sudan','East-Central Africa',FALSE],
            ['Spain','Southern Europe',FALSE],
            ['Sri Lanka','South-Central Asia',FALSE],
            ['Sudan','Northern Africa',FALSE],
            ['Suriname','North-Eastern South America',FALSE],
            ['Swaziland [Eswatini]','Southern Africa',FALSE],
            ['Sweden','Northern Europe',FALSE],
            ['Switzerland','Western Europe',FALSE],
            ['Syria','Middle East',FALSE],
            ['Taiwan [Republic of China]','Eastern Asia',FALSE],
            ['Tajikistan','Central Asia',FALSE],
            ['Tanzania; officially the United Republic of Tanzania','Eastern Africa',FALSE],
            ['Thailand','South-East Asia',FALSE],
            ['Tibet','South-Central Asia',FALSE],
            ['Timor-Leste [East Timor]','South-East Asia',FALSE],
            ['Togo','West Africa',FALSE],
            ['Tokelau','Oceania',FALSE],
            ['Tonga','Oceania',FALSE],
            ['Trinidad and Tobago','Caribbean',FALSE],
            ['Tunisia','Northern Africa',FALSE],
            ['Turkey','Middle East',FALSE],
            ['Turkmenistan','Central Asia',FALSE],
            ['Turks and Caicos Islands','Caribbean',FALSE],
            ['Tuvalu','Oceania',FALSE],
            ['Uganda','Eastern Africa',FALSE],
            ['Ukraine','Eastern Europe',FALSE],
            ['United Arab Emirates','Middle East',FALSE],
            ['United Kingdom','Northern Europe',FALSE],
            ['United States','North America',FALSE],
            ['Uruguay','Central East South America',FALSE],
            ['Uzbekistan','Central Asia',FALSE],
            ['Vanuatu','Oceania',FALSE],
            ['Vatican City State [Holy See]','Southern Europe',FALSE],
            ['Venezuela','South America',FALSE],
            ['Vietnam','South-East Asia',FALSE],
            ['Virgin Islands [British]','Caribbean',FALSE],
            ['Virgin Islands [U.S.]','Caribbean',FALSE],
            ['Wallis and Futuna Islands','Oceania',FALSE],
            ['Western Sahara','Northern Africa',FALSE],
            ['Yemen','Middle East',FALSE],
            ['Zambia','Eastern Africa',FALSE],
            ['Zimbabwe','Eastern Africa',FALSE]
        ];
        //
        foreach($countries as $country){
            Countries::factory()->create([
                'country' => $country[0],
                'region' => $country[1],
                'active' => $country[2]
            ]);
        }
    }
}
